Bookcase/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
path('admin/', admin.site.urls),
    path('', include('usuario.urls')),
    path('', include('libro.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

libro/urls.py
from django.urls import path, include
from . import views

app_name = 'libro'

urlpatterns = [

]

usuario/urls.py
from django.urls import path, include
from . import views

app_name = 'usuario'

urlpatterns = [
    path('', views.bienvenida, name="bienvenida"),
    path('registro/', views.registro, name="api"),
    path(r'^accounts/login', views.inicioSesion, name='inicioSesion'),
    path('accounts/logout', views.salir, name="logout"),
    path('home/', views.home, name="home"),
    path('libro/<int:id_libro>', views.libro, name="libro"),
    path('eliminarLibro/<int:id_libro>', views.eliminarLibro, name="eliminarLibro"),
    path('genero/<int:id_genero>', views.genero, name="genero"),
    path('registro', views.registro, name="registro"),
    path('perfil/', views.miPerfil, name="perfil"),
    path('libros/', views.librosGenero, name="libros"),
    path('apiLibros/', views.apiLibrosGenero, name="apiLibros"),
    path('buscador/', views.buscador, name="buscador"),
    path('explorador/', views.explorador, name="explorador"),
    path('apiFavoritos/', views.librosGenerosUsuario, name='favoritos'),
    path('autores/<str:caracter>/', views.autores, name="autores"),
    path('autor/<int:id_autor>', views.autor, name="autor"),
    path('autoresApi/', views.autoresApi, name="autoresApi"),
    path('librerias/', views.libreria, name="librerias"),
    path('libreria/<int:id_libreria>', views.libreriaIndividual, name="libreria"),
    path('añadirLibro/<int:id_libro>/', views.añadirLibro, name="añadir"),
    path('borrar/<int:id_libreria>', views.borrar, name="borrar"),
    path('add/', views.add, name="add"),
    path('addBook/', views.addBook, name="addBook"),
    path('addAutor/', views.addAutor, name="addAutor"),
    path('addGenero/', views.addGenero, name="addGenero"),
    path('editLibro/', views.editLibro, name="editLibro"),
    path('editAutor/', views.editAutor, name="editAutor"),
    path('editGenero/', views.editGenero, name="editGenero"),
    path('lista/<int:lista>', views.listas, name="lista"),
    path('politica/', views.politica, name="politica")
]

templates/bienvenida/bienvenida.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Bienvenida</title>
    {% load static %}
    {%block css%}
        <title>BookCase</title>
        <link rel="stylesheet" type="text/css" href="{% static 'bienvenida.css' %}">
    {%endblock%}

</head>
{% block content %}
{% load static %}
<body>
    <header class="contenedor">
        <nav class="navbar logoRI">
            <a class="navbar-brand" href="#"><img src="{% static 'imagenes/logo/logo.png' %}" width="150px"></a>
            <form class="form-inline">
                <a class="btn " href="{% url 'usuario:registro' %}">Registro</a>
                <a class="btn  m-1" href="{% url 'usuario:inicioSesion' %}">Inicia sesion</a>
            </form>
        </nav>
        <div class="contains">
            <h1 class="slogan">
                Ten tus librerías con tus libros favoritos más a mano con BookCase.
            </h1>
        </div>
    </header>
    <div class="container-fluid">
        <div class="container">
            <div class="info">
                <h2>Descubre libros nuevos con nuestra aplicación</h2>
                <p class="textInfo">Utiliza nuestra página web BookCase para conocer nuevos libros. Descubre libros que sean afínes a tí.
                Encuentra tus libros de una forma rápida y sencilla</p>
            </div>
            <div class="row text-center elementos"><br>
                <div class="col-md-4 col-sm-4 rodona">
                    <div class="rounded-circle redonda"><i class="fas fa-book" style="font-size:90px;color:white;"></i></div>
                    <h5 class="stitol" id="hosting">BookCase</h5>
                    <p class="pserveis">Descubre los mejores libros para ti. Organiza tus libros. Elige los generos que más te gustan. Nosotros nos encargamos de sugerirte libros compatibles contigo.</p>
                </div>
                <div class="col-md-4 col-sm-4 rodona">
                    <div class="rounded-circle redonda"><i class="fa fa-list-ul" style="font-size:90px;color:white;"></i></div>
                    <h5 class="stitol">Listas</h5>
                    <p class="pserveis">Añade los libros a listas que hemos definido para que los tengas organizados. Tendás una lista para tus libros leídos, una para libros que quieres leer, ...</p>
                </div>
                <div class="col-md-4 col-sm-4 rodona">
                    <div class="rounded-circle redonda"><i class="fas fa-book-reader" style="font-size:90px;color:white;"></i></div>
                    <h5 class="stitol">Librerías</h5>
                    <p class="pserveis">Crea tus librerías con los libros que más te gusten, como si fuera una librería real. Organiza tus libros visualmente para tenerlos más a mano.</p>
                </div>
            </div>
        </div>
        <div>
            <div class="container">
                <h2>Ejemplo de lo que vas a encontrar en BookCase</h2>
                <div class="row ejemplos">
                    <div class="col-12 col-md-4">
                        <img width="100%" src="{% static 'imagenes/mb.PNG' %}">
                    </div>
                    <div class="col-12 col-md-6">
                        <img width="100%" src="{% static 'imagenes/tb.PNG' %}">
                    </div>

                </div>
            </div>

        </div>
    </div>
    <!-- Footer -->
	<section id="footer">
		<div class="container container-footer">
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
					<ul class="list-unstyled list-inline social text-center">
						<li class="list-inline-item"><a href="https://www.facebook.com/ecaroortega2"><i class="fab fa-facebook-square"></i></a></li>
						<li class="list-inline-item"><a href="https://twitter.com/estefiy"><i class="fab fa-twitter-square"></i></a></li>
						<li class="list-inline-item"><a href="https://www.instagram.com/estefy950/"><i class="fab fa-instagram"></i></a></li>
						<li class="list-inline-item"><a href="https://github.com/estefania95"><i class="fab fa-github-square"></i></a></li>
					</ul>
				</div>
				</hr>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
					<p><a href="{% url 'usuario:politica' %}">Política de privacidad</a></p>
					<p class="h6">&copyBookCase</p>
				</div>
				</hr>
			</div>
		</div>
	</section>
	<!-- ./Footer -->
</body>
{% endblock %}
</html>