Bookcase/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
path('admin/', admin.site.urls),
    path('', include('usuario.urls')),
    path('', include('libro.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

libro/urls.py
from django.urls import path, include
from . import views

app_name = 'libro'

urlpatterns = [

]

usuario/urls.py
from django.urls import path, include
from . import views

app_name = 'usuario'

urlpatterns = [
    path('', views.bienvenida, name="bienvenida"),
    path('registro/', views.registro, name="api"),
    path(r'^accounts/login', views.inicioSesion, name='inicioSesion'),
    path('accounts/logout', views.salir, name="logout"),
    path('home/', views.home, name="home"),
    path('libro/<int:id_libro>', views.libro, name="libro"),
    path('eliminarLibro/<int:id_libro>', views.eliminarLibro, name="eliminarLibro"),
    path('genero/<int:id_genero>', views.genero, name="genero"),
    path('registro', views.registro, name="registro"),
    path('perfil/', views.miPerfil, name="perfil"),
    path('libros/', views.librosGenero, name="libros"),
    path('apiLibros/', views.apiLibrosGenero, name="apiLibros"),
    path('buscador/', views.buscador, name="buscador"),
    path('explorador/', views.explorador, name="explorador"),
    path('apiFavoritos/', views.librosGenerosUsuario, name='favoritos'),
    path('autores/<str:caracter>/', views.autores, name="autores"),
    path('autor/<int:id_autor>', views.autor, name="autor"),
    path('autoresApi/', views.autoresApi, name="autoresApi"),
    path('librerias/', views.libreria, name="librerias"),
    path('libreria/<int:id_libreria>', views.libreriaIndividual, name="libreria"),
    path('añadirLibro/<int:id_libro>/', views.añadirLibro, name="añadir"),
    path('borrar/<int:id_libreria>', views.borrar, name="borrar"),
    path('add/', views.add, name="add"),
    path('addBook/', views.addBook, name="addBook"),
    path('addAutor/', views.addAutor, name="addAutor"),
    path('addGenero/', views.addGenero, name="addGenero"),
    path('editLibro/', views.editLibro, name="editLibro"),
    path('editAutor/', views.editAutor, name="editAutor"),
    path('editGenero/', views.editGenero, name="editGenero"),
    path('lista/<int:lista>', views.listas, name="lista"),
    path('politica/', views.politica, name="politica")
]

libro/models.py
from django.db import models

# Create your models here.

class Genero(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    nombreImagen = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.nombre


class Libro(models.Model):
    titulo = models.CharField(max_length=100)
    isbn = models.CharField(max_length=50)
    editorial = models.CharField(max_length=100)
    numeroPaginas = models.IntegerField()
    anoEdicion = models.IntegerField()
    sinopsis = models.TextField()
    imagen = models.CharField(max_length=200, null=True, blank=True)
    genero = models.ManyToManyField(Genero)

    def __str__(self):
        return self.titulo


class Autor(models.Model):
    nombre = models.CharField(max_length=100, null=True, blank=True)
    apellidos = models.CharField(max_length=100, null=True, blank=True)
    anoNacimiento = models.IntegerField(null=True, blank=True)
    descripcion = models.TextField(null=True, blank=True)
    libro = models.ManyToManyField(Libro, null=True, blank=True)

    def __str__(self):
        return self.nombre

libro/views.py
from django.shortcuts import render

# Create your views here.

templates/web/autor.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    {% load static %}
    {%block css%}
    <title>BookCase</title>
        <link rel="stylesheet" href="{% static 'css/home.css' %}">
    {%endblock%}
</head>
{% block content %}
{% load static %}
<body>
  <!-- Navegador -->
  <nav class="navbar navbar-light navbar-dark bg-dark navegador">
      <a class="navbar-brand" href="{% url 'usuario:home' %}"><img src="{% static 'imagenes/logo/logo.png' %}" width="150px"></a>
      <div class="btn-group usuario">
          <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" data-display="static" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-user-circle"></i>
          </button>
           <div class="dropdown-menu dropdown-menu-right ">
              <a class="dropdown-item " href="{% url 'usuario:perfil' %}">Mi Perfil</a>
                {% if admin %}
                    <a class="dropdown-item" href="{% url 'usuario:add' %}">Añadir o editar</a>
               {% endif %}
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'usuario:logout' %}">Cerrar sesión</a>
          </div>
      </div>
  </nav>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top navegador">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample08" aria-controls="navbarsExample08" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample08">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'usuario:home' %}">INICIO <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'usuario:libros' %}">LIBROS</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'usuario:explorador' %}">EXPLORAR</a>
          </li>
            <li class="nav-item">
                <a class="nav-link " href="{% url 'usuario:autores' 'A' %}">AUTORES</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="{% url 'usuario:librerias' %}">MIS LIBRERIAS</a>
            </li>
        </ul>
      </div>

      <form class="form-inline" action="{% url 'usuario:buscador' %}" method="GET">
          {% csrf_token %}
        <input class="form-control mr-sm-2" name="libro" id="buscador" type="search" placeholder="Buscar" aria-label="Search">
        <button class="btn my-2 my-sm-0" type="submit">Buscar</button>
      </form>

    </nav>
  <!-- Fin navegador -->
<div class="container">
    <h1>{{ autor.nombre }} {{ autor.apellidos }}</h1>
    <p><strong>Año de nacimiento: </strong>{{ autor.anoNacimiento }}</p>
    <p><strong>Descripción</strong></p>
    <p>{{ autor.descripcion }}</p>

    <h4>Libros de {{ autor.nombre }} {{ autor.apellidos }}</h4>
    <div class="row">
        {% for libro in librosAutor %}
          <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 p-0">
              <div>
                  <img src="{{ libro.imagen }}" style="height: 320px">
                  <p><a href="{% url 'usuario:libro' libro.id %}">{{ libro.titulo }}</a></p>
              </div>
          </div>
          {% endfor %}
    </div>
</div>
<!-- Footer -->
	<section id="footer">
		<div class="container container-footer">
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
					<ul class="list-unstyled list-inline social text-center">
						<li class="list-inline-item"><a href="https://www.facebook.com/ecaroortega2"><i class="fab fa-facebook-square"></i></a></li>
						<li class="list-inline-item"><a href="https://twitter.com/estefiy"><i class="fab fa-twitter-square"></i></a></li>
						<li class="list-inline-item"><a href="https://www.instagram.com/estefy950/"><i class="fab fa-instagram"></i></a></li>
						<li class="list-inline-item"><a href="https://github.com/estefania95"><i class="fab fa-github-square"></i></a></li>
					</ul>
				</div>
				</hr>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
					<p><a href="{% url 'usuario:politica' %}">Política de privacidad</a></p>
					<p class="h6">&copyBookCase</p>
				</div>
				</hr>
			</div>
		</div>
	</section>
	<!-- ./Footer -->
</body>
{% endblock %}
</html>

templates/web/home.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    {% load static %}
    {%block css%}
    <title>BookCase</title>
        <link rel="stylesheet" href="{% static 'css/home.css' %}">
    {%endblock%}
</head>
{% block content %}
{% load static %}
<body>
  <!-- Navegador -->
  <nav class="navbar navbar-light navbar-dark bg-dark navegador">
      <a class="navbar-brand" href="{% url 'usuario:home' %}"><img src="{% static 'imagenes/logo/logo.png' %}" width="150px"></a>
      <div class="btn-group usuario">
          <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" data-display="static" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-user-circle"></i>
          </button>
           <div class="dropdown-menu dropdown-menu-right ">
              <a class="dropdown-item " href="{% url 'usuario:perfil' %}">Mi Perfil</a>
                {% if admin %}
                    <a class="dropdown-item" href="{% url 'usuario:add' %}">Añadir o editar</a>
               {% endif %}
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'usuario:logout' %}">Cerrar sesión</a>
          </div>
      </div>
  </nav>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top navegador">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample08" aria-controls="navbarsExample08" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample08">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'usuario:home' %}">INICIO <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'usuario:libros' %}">LIBROS</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'usuario:explorador' %}">EXPLORAR</a>
          </li>
            <li class="nav-item">
                <a class="nav-link " href="{% url 'usuario:autores' 'A' %}">AUTORES</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="{% url 'usuario:librerias' %}">MIS LIBRERIAS</a>
            </li>
        </ul>
      </div>

      <form class="form-inline" action="{% url 'usuario:buscador' %}" method="GET">
          {% csrf_token %}
        <input class="form-control mr-sm-2" name="libro" id="buscador" type="search" placeholder="Buscar" aria-label="Search">
        <button class="btn my-2 my-sm-0" type="submit">Buscar</button>
      </form>

    </nav>
  <!-- Fin navegador -->
  <div class="banner">
      <img class="imgBanner" src="{% static 'imagenes/banner.png' %}">
  </div>
  <!-- Contenedor -->
  <div class="superior">
    <div class="container contenedor">

        <!-- Inicio Generos -->
     <div class="divGen">
        <i class="fas fa-angle-right icono"></i>
        <h3>Generos</h3>
     </div>
    <div class="carousel slide" data-ride="carousel" id="multi_item">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <div class="row contenGen">
                <div class="col-12 col-md-2">
                    <a href="{% url 'usuario:genero' 1 %}">
                        <img class="d-block w-100 generoImg" src="{% static 'generos/historia.jpg' %}" alt="1 slide" height="auto">
                    </a>
                    <p></p>
                </div>
                <div class="col-12 col-md-2">
                        <a href="{% url 'usuario:genero' 2 %}">
                            <img class="d-block w-100 generoImg" src="{% static 'generos/historica.jpg' %}" alt="1 slide" height="auto">
                        </a>
                        <p></p>
                    </div>
                <div class="col-12 col-md-2">
                        <a href="{% url 'usuario:genero' 3 %}">
                            <img class="d-block w-100 generoImg" src="{% static 'generos/contemporanea.jpg' %}" alt="1 slide" height="auto">
                        </a>
                        <p></p>
                    </div>
                <div class="col-12 col-md-2">
                        <a href="{% url 'usuario:genero' 4 %}">
                            <img class="d-block w-100 generoImg" src="{% static 'generos/autoayuda.jpg' %}" alt="1 slide" height="auto">
                        </a>
                        <p></p>
                    </div><div class="col-12 col-md-2">
                        <a href="{% url 'usuario:genero' 5 %}">
                            <img class="d-block w-100 generoImg" src="{% static 'generos/comics.jpg' %}" alt="1 slide" height="auto">
                        </a>
                        <p></p>
                    </div>
        </div>
      </div>
      <div class="carousel-item">
        <div class="row contenGen">
            <div class="col-12 col-md-2">
                        <a href="{% url 'usuario:genero' 6 %}">
                            <img class="d-block w-100 generoImg" src="{% static 'generos/novelaNegra.jpg' %}" alt="1 slide" height="auto">
                        </a>
                        <p></p>
                    </div>
              <div class="col-12 col-md-2">
                    <a href="{% url 'usuario:genero' 7 %}">
                        <img class="d-block w-100 generoImg" src="{% static 'generos/juvenil.jpg' %}" alt="1 slide" height="auto">
                    </a>
                    <p></p>
                </div>
                <div class="col-12 col-md-2">
                        <a href="{% url 'usuario:genero' 8 %}">
                            <img class="d-block w-100 generoImg" src="{% static 'generos/infantil.jpg' %}" alt="1 slide" height="auto">
                        </a>
                        <p></p>
                    </div>
                <div class="col-12 col-md-2">
                        <a href="{% url 'usuario:genero' 9 %}">
                            <img class="d-block w-100 generoImg" src="{% static 'generos/literatura.jpg' %}" alt="1 slide" height="auto">
                        </a>
                        <p></p>
                    </div>
                <div class="col-12 col-md-2">
                        <a href="{% url 'usuario:genero' 10 %}">
                            <img class="d-block w-100 generoImg" src="{% static 'generos/novelaRomantica.jpg' %}" alt="1 slide" height="auto">
                        </a>
                        <p></p>
                    </div>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#multi_item" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#multi_item" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <!-- Fin Generos -->
    <div class="divGen">
        <i class="fas fa-angle-right icono"></i>
        <h3>Libros más nuevos</h3>
    </div>

      <div class="row">
          {% for libro in librosNuevos %}
          <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 p-0">
              <div class="libroContainer">
                  <a href="{% url 'usuario:libro' libro.id %}"><img src="{{ libro.imagen }}" style="height: 320px">
                      <p>{{ libro.titulo }}</p></a>
              </div>
          </div>
          {% endfor %}
      </div>
     <div class="divGen">
        <i class="fas fa-angle-right icono"></i>
        <h3>Libros recomendados</h3>
     </div>
      <div class="row">
          {% for libro in librosRecomendados %}
          <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 p-0">
              <div class="libroContainer">
                  <a href="{% url 'usuario:libro' libro.id %}">
                  <img src="{{ libro.imagen }}" style="height: 320px">
                      <p>{{ libro.titulo }}</p></a>
              </div>
          </div>
          {% endfor %}
      </div>
  </div>
  </div>
  <!-- Footer -->
	<section id="footer">
		<div class="container container-footer">
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
					<ul class="list-unstyled list-inline social text-center">
						<li class="list-inline-item"><a href="https://www.facebook.com/ecaroortega2"><i class="fab fa-facebook-square"></i></a></li>
						<li class="list-inline-item"><a href="https://twitter.com/estefiy"><i class="fab fa-twitter-square"></i></a></li>
						<li class="list-inline-item"><a href="https://www.instagram.com/estefy950/"><i class="fab fa-instagram"></i></a></li>
						<li class="list-inline-item"><a href="https://github.com/estefania95"><i class="fab fa-github-square"></i></a></li>
					</ul>
				</div>
				</hr>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
					<p><a href="{% url 'usuario:politica' %}">Política de privacidad</a></p>
					<p class="h6">&copyBookCase</p>
				</div>
				</hr>
			</div>
		</div>
	</section>
	<!-- ./Footer -->
<script src="{% static 'JS/home.js' %}"></script>
</body>
{% endblock %}
</html>

templates/web/libro.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    {% load static %}
    {%block css%}
    <title>BookCase</title>
        <link rel="stylesheet" href="{% static 'css/libro.css' %}">
    {%endblock%}
</head>
{% block content %}
{% load static %}
<body>

 <!-- Navegador -->
  <nav class="navbar navbar-light navbar-dark bg-dark navegador">
      <a class="navbar-brand" href="{% url 'usuario:home' %}"><img src="{% static 'imagenes/logo/logo.png' %}" width="150px"></a>
      <div class="btn-group usuario">
          <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" data-display="static" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-user-circle"></i>
          </button>
           <div class="dropdown-menu dropdown-menu-right ">
              <a class="dropdown-item " href="{% url 'usuario:perfil' %}">Mi Perfil</a>
                {% if admin %}
                    <a class="dropdown-item" href="{% url 'usuario:add' %}">Añadir o editar</a>
               {% endif %}
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'usuario:logout' %}">Cerrar sesión</a>
          </div>
      </div>
  </nav>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top navegador">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample08" aria-controls="navbarsExample08" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample08">
        <ul class="navbar-nav">
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'usuario:home' %}">INICIO <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'usuario:libros' %}">LIBROS</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'usuario:explorador' %}">EXPLORAR</a>
          </li>
            <li class="nav-item">
                <a class="nav-link " href="{% url 'usuario:autores' 'A' %}">AUTORES</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="{% url 'usuario:librerias' %}">MIS LIBRERIAS</a>
            </li>
        </ul>
      </div>

      <form class="form-inline" action="{% url 'usuario:buscador' %}" method="GET">
          {% csrf_token %}
        <input class="form-control mr-sm-2" name="libro" id="buscador" type="search" placeholder="Buscar" aria-label="Search">
        <button class="btn my-2 my-sm-0" type="submit">Buscar</button>
      </form>

    </nav>
  <!-- Fin navegador -->
<div class="container contenedor">
    <h1>{{ libro.titulo }}</h1>
    <div class="containLibro">
        <div>
            <img src="{{ libro.imagen }}">
        </div>
        <div class="sinopsis">
            <h3>Sinopsis</h3>
            <p>{{ libro.sinopsis }}</p>
            <div class="botones">
                {% if lista %}
                    <button type="button" class="btn" data-toggle="modal" data-target="#lista"><i class="fas fa-check"></i>   {{ estado }} <i class="fas fa-caret-down"></i></button>
                {% else %}
                    <button type="button" class="btn" data-toggle="modal" data-target="#lista">Añadir a mi lista</button>
                {% endif %}
                {% if librerias %}
                    <button type="button" class="btn" data-toggle="modal" data-target="#libreria">Añadir a libreria</button>
                {% endif %}
            </div>
        </div>
    </div>

          <!-- Modal -->
            <div class="modal fade" id="lista" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <form method="POST" action="{% url 'usuario:libro' libro.id %}">
                    {% csrf_token %}
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Añadir a mi lista</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                          {{ form.estado }}
                      </div>
                      <div class="modal-footer">
                          {% if lista %}
                              <a href="{% url 'usuario:eliminarLibro' libro.id %}" class="btn btn-danger">Eliminar</a>
                          {% endif %}
                        <button type="submit" class="btn">Guardar</button>
                      </div>
                    </div>
                </form>
              </div>
            </div>

          <!-- Modal -->
            <div class="modal fade" id="libreria" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <form method="POST" action="{% url 'usuario:añadir' libro.id %}">
                    {% csrf_token %}
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Añadir a libreria</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                          <select name="librerias">
                              {% for libreria in librerias %}
                                  {% if libreria.libro.count < libreria.maxLibros %} %}
                                    <option name="libreria" value="{{ libreria.id }}">{{ libreria.nombre }}</option>
                                  {% endif %}
                              {% endfor %}
                          </select>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn" data-dismiss="modal">Cerrar</button>
                        <button type="submit" class="btn">Guardar</button>
                      </div>
                    </div>
                </form>
              </div>
            </div>

</div>
<!-- Footer -->
	<section id="footer">
		<div class="container container-footer">
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
					<ul class="list-unstyled list-inline social text-center">
						<li class="list-inline-item"><a href="https://www.facebook.com/ecaroortega2"><i class="fab fa-facebook-square"></i></a></li>
						<li class="list-inline-item"><a href="https://twitter.com/estefiy"><i class="fab fa-twitter-square"></i></a></li>
						<li class="list-inline-item"><a href="https://www.instagram.com/estefy950/"><i class="fab fa-instagram"></i></a></li>
						<li class="list-inline-item"><a href="https://github.com/estefania95"><i class="fab fa-github-square"></i></a></li>
					</ul>
				</div>
				</hr>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
					<p><a href="{% url 'usuario:politica' %}">Política de privacidad</a></p>
					<p class="h6">&copyBookCase</p>
				</div>
				</hr>
			</div>
		</div>
	</section>
	<!-- ./Footer -->
</body>
{% endblock %}
</html>