Bookcase/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
path('admin/', admin.site.urls),
    path('', include('usuario.urls')),
    path('', include('libro.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

libro/urls.py
from django.urls import path, include
from . import views

app_name = 'libro'

urlpatterns = [

]

usuario/urls.py
from django.urls import path, include
from . import views

app_name = 'usuario'

urlpatterns = [
    path('', views.bienvenida, name="bienvenida"),
    path('registro/', views.registro, name="api"),
    path(r'^accounts/login', views.inicioSesion, name='inicioSesion'),
    path('accounts/logout', views.salir, name="logout"),
    path('home/', views.home, name="home"),
    path('libro/<int:id_libro>', views.libro, name="libro"),
    path('eliminarLibro/<int:id_libro>', views.eliminarLibro, name="eliminarLibro"),
    path('genero/<int:id_genero>', views.genero, name="genero"),
    path('registro', views.registro, name="registro"),
    path('perfil/', views.miPerfil, name="perfil"),
    path('libros/', views.librosGenero, name="libros"),
    path('apiLibros/', views.apiLibrosGenero, name="apiLibros"),
    path('buscador/', views.buscador, name="buscador"),
    path('explorador/', views.explorador, name="explorador"),
    path('apiFavoritos/', views.librosGenerosUsuario, name='favoritos'),
    path('autores/<str:caracter>/', views.autores, name="autores"),
    path('autor/<int:id_autor>', views.autor, name="autor"),
    path('autoresApi/', views.autoresApi, name="autoresApi"),
    path('librerias/', views.libreria, name="librerias"),
    path('libreria/<int:id_libreria>', views.libreriaIndividual, name="libreria"),
    path('añadirLibro/<int:id_libro>/', views.añadirLibro, name="añadir"),
    path('borrar/<int:id_libreria>', views.borrar, name="borrar"),
    path('add/', views.add, name="add"),
    path('addBook/', views.addBook, name="addBook"),
    path('addAutor/', views.addAutor, name="addAutor"),
    path('addGenero/', views.addGenero, name="addGenero"),
    path('editLibro/', views.editLibro, name="editLibro"),
    path('editAutor/', views.editAutor, name="editAutor"),
    path('editGenero/', views.editGenero, name="editGenero"),
    path('lista/<int:lista>', views.listas, name="lista"),
    path('politica/', views.politica, name="politica")
]

templates/registro/registro.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    {%block css%}
        <title>BookCase</title>
        <link rel="stylesheet" type="text/css" href="{% static 'registro.css' %}">
    {%endblock%}
</head>
{% block content %}
{% load static %}
<body>
    <div class="contenedor">
        <div class="imagen ">
            <a class="navbar-brand logo" href="{% url 'usuario:bienvenida' %}">
                <img src="{% static 'imagenes/logo/logo.png' %}" width="150px">
            </a>
            <div class="conteTexto">
                <div class="texto">
                    <ul>
                        <li>Registrate a BookCase para conocer nuevos libros.</li>
                        <li>Descubre libros que sean afínes a tí.</li>
                        <li>Encuentra tus libros de una forma rápida y sencilla.</li>
                        <li>Crea tus librerías con los libros que más te gusten, como si fuera una librería real.</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="registro">
            <h2>REGÍSTRATE</h2>
            <div class="contentForm">
                <form method="POST" action="{% url 'usuario:registro' %}">
                    {% csrf_token %}
                   <div>
                        <input type="text" class="form-control formulario" id="usuario" name="username" aria-describedby="Usuario" placeholder="Usuario">
                    </div>
                    <div>
                        <input type="text" class="form-control formulario" id="email" aria-describedby="email" name="email" placeholder="Email">
                    </div>
                    <div><input type="password" class="form-control formulario" id="usuario" aria-describedby="password1" name="password1" placeholder="Contraseña"></div>
                    <div><input type="password" class="form-control formulario" id="usuario" aria-describedby="password2" name="password2" placeholder="Repite la contraseña"></div>
                    <button type="submit" class="btn formulario">Registrar</button>
                </form>
            </div>
            <a href="{% url 'usuario:inicioSesion' %}">Ya tienes cuenta?</a>
        </div>
    </div>
</body>
{% endblock %}
</html>